name: suisse
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Harm Aarts <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  crypto: any

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mock_web_server: ^4.0.0
