name: suisse
description: Library for communicating with the BitcoinSuisse API
version: 0.1.1
author: Harm Aarts <harm@aarts.email>
homepage: https://github.com/haarts/bitcoin_suisse_client

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  crypto: ^2.0.6
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0
  mock_web_server: ^4.0.0
